const promptData = [
    "Sing a few lines of your go to karaoke song",
"Drop it like it's hot",
"Never Have I Ever (3 fingers)",
"Make a story by each player adding a word. Whoever ends the sentence ",
"Have the player to your right post a story and tag us",
"Do an impression of one of the players.",
"Hold hands with the player to your right for the next 3 minutes",
"Tell everyone about your first childhood crush",
"What is your first memory?",
"What is the last dream you can remember?",
"Tell everyone about your favorite piece of art",
"Answer who you think is the hottest person playing the game",
"You must swap an article of clothing with the person to your left",
"You must give everyone playing a compliment",
"Tell each person playing the first thing you noticed about them",
"Tell an embarassing story",
"Tell everyone about your worst date",
"Tell everyone about a time you lied",
"Twerk for 5 seconds",
"Try to start a conversation with a stranger either virtually or in person",
"What is your best vacation memory?",
"Do 10 squats",
"Decide on a positive habit that you must do everyday for the next week",
"Lip Sync a Beyonce song of your choice",
"Give someone of your choice a lap dance",
"Perform your signature dance move",
"Say a word and go around in a circle trying to rhyme. ",
"Say a category and go around in a circle naming things of that category.",
"What qualities do you like best about people",
"What do you think your best quality is?",
"Give everyone playing a kiss on the forehead",
"Give everyone playing a kiss wherever you like",
"Close your eyes and try to say everyone playing's eye color.",
"Say the number of siblings each player has.",
"Close your eyes and say what everyone playing is wearing.",
"For each player, guess a TV show they have watched fully through (must be different).",
"For each player, guess a movie that have seen (must be different).",
"What is your favorite compliment to get?",
"What is your favorite inspirational quote?",
"What is the best view you have ever seen?",
"What is your own worst red flag?",
"What do you find to be the worst red flag?",
"If you made your own TV show, what would it be about?",
"If you wrote a book, what would it be about?",
"If an actor were to do a voice over for your life, who would you choose?",
"If an actor played you in a movie, who would it be?",
"What is your most unrealistic dream job?",
  ];
  
  export default promptData;